import type { Metadata } from "next";
import { Inter, Gluten } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Nav from "@/components/layout/Nav";

const inter = Inter({ subsets: ["latin"] });
const gluten = Gluten({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={gluten.className}>
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
