import type { Metadata } from "next";
import { Inter, Gluten } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Nav from "@/components/layout/Nav";
import AnimatedCursor from "react-animated-cursor"



const gluten = Gluten({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={gluten.className}>
   
      <AnimatedCursor
      innerSize={8}
      outerSize={8}
      color='165, 128, 220'
      outerAlpha={0.2}
      innerScale={0.7}
      outerScale={5}
     
    trailingSpeed={3}
      />
        <Providers>
          <Nav />
          {children}
        </Providers>
      
      </body>
    </html>
  );
}
